"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const express_validator_1 = require("express-validator");
const register_validation_1 = require("../utils/validation_schemas/register_validation");
const register_middleware_1 = require("../utils/middlewares/register_middleware");
const login_validation_1 = require("../utils/validation_schemas/login_validation");
const login_middlewares_1 = require("../utils/middlewares/login_middlewares");
const token_middleware_1 = require("../utils/middlewares/token_middleware");
const validation_middleware_1 = require("../utils/middlewares/validation_middleware");
const token_validation_1 = require("../utils/validation_schemas/token_validation");
const users_1 = require("../utils/middlewares/users");
const router = (0, express_1.Router)();
router.post('/auth/register', (0, express_validator_1.checkSchema)(register_validation_1.REGISTER_VALIDATION_SCHEMA), validation_middleware_1.validation_middleware, register_middleware_1.register_middleware);
router.post('/auth/login', (0, express_validator_1.checkSchema)(login_validation_1.LOGIN_VALIDATION_SCHEMA), validation_middleware_1.validation_middleware, login_middlewares_1.login_middleware);
router.delete('/auth/account', validation_middleware_1.auth_validation_middleware, users_1.delete_user_middleware);
router.post('/auth/token', token_middleware_1.token_middleware);
router.post('/auth/check-token', (0, express_validator_1.checkSchema)(token_validation_1.TOKEN_VALIDATION_SCHEMA), validation_middleware_1.validation_middleware, token_middleware_1.check_token_middleware);
router.post('/auth/logout', validation_middleware_1.auth_validation_middleware, login_middlewares_1.logout_middleware);
exports.default = router;
